### ISSUE TITLE
TypeError: LlamaForSequenceClassification.forward() got an unexpected keyword argument 'token_type_ids'

### ISSUE THREAD

**Issue by frieda-huang** [meta-llama/llama-stack-apps#89]
Running `PYTHONPATH=. mesop app/main.py` results in the following error regarding 'token_type_ids'. It seems to be related to the transformers package as shown [here](https://github.com/huggingface/transformers/issues/24514), but after I updating to the latest version, the same error still occurs.

```
Traceback (most recent call last):
  File "/Users/friedahuang/local/llama-stack/llama_stack/distribution/server/server.py", line 215, in sse_generator
    async for item in event_gen:
  File "/Users/friedahuang/local/llama-stack/llama_stack/providers/impls/meta_reference/agents/agents.py", line 127, in create_agent_turn
    async for event in agent.create_and_execute_turn(request):
  File "/Users/friedahuang/local/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 174, in create_and_execute_turn
    async for chunk in self.run(
  File "/Users/friedahuang/local/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 239, in run
    async for res in self.run_multiple_shields_wrapper(
  File "/Users/friedahuang/local/llama-stack/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 294, in run_multiple_shields_wrapper
    await self.run_multiple_shields(messages, shields)
  File "/Users/friedahuang/local/llama-stack/llama_stack/providers/impls/meta_reference/agents/safety.py", line 37, in run_multiple_shields
    responses = await asyncio.gather(
  File "/Users/friedahuang/local/llama-stack/llama_stack/distribution/routers/routers.py", line 168, in run_shield
    return await self.routing_table.get_provider_impl(shield_type).run_shield(
  File "/Users/friedahuang/local/llama-stack/llama_stack/providers/impls/meta_reference/safety/safety.py", line 65, in run_shield
    res = await shield.run(messages)
  File "/Users/friedahuang/local/llama-stack/llama_stack/providers/impls/meta_reference/safety/shields/base.py", line 54, in run
    return await self.run_impl(text)
  File "/Users/friedahuang/local/llama-stack/llama_stack/providers/impls/meta_reference/safety/shields/prompt_guard.py", line 84, in run_impl
    outputs = self.model(**inputs)
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/llamastack-my-local-stack/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: LlamaForSequenceClassification.forward() got an unexpected keyword argument 'token_type_ids'
```

**Comment by japsingh** [comment]
I am also facing the same problem, while trying to run  examples.agents.*

**Comment by tuckkin** [comment]
Same here...

**Comment by yanxi0830** [comment]
This is caused by issue with shield `prompt_guard`, and we have removed it recently. Could you try to pull the latest llama-stack` repo or [llama-stack 0.0.41](https://pypi.org/project/llama-stack/). You could also use the `--disable-safety` flag to skip running safety shields to bypass the issue for all examples.

**Comment by frieda-huang** [comment]
> > This is caused by issue with shield `prompt_guard` for safety, and we have removed it recently. Could you try to pull the latest `llama-stack` repo or [llama-stack 0.0.41](https://pypi.org/project/llama-stack/). You could also use the `--disable-safety` flag to skip running safety shields to bypass the issue for all examples.
> 
> After updating it to 0.0.42, it looks like I encounter the same old issue of `routing_key` again.
> 
> ```
> python3 -m examples.agents.vacation localhost 11434
> > created agents with agent_id=2b0da742-9ebb-45f2-8ff9-b2874ada0e7b
> User> I am planning a trip to Switzerland, what are the top 3 places to visit?
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/Users/friedahuang/Documents/llama-stack-apps/examples/agents/vacation.py", line 58, in <module>
>     fire.Fire(main)
>   File "/Users/friedahuang/Desktop/moonshot-v2/.conda/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/friedahuang/Desktop/moonshot-v2/.conda/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>                                 ^^^^^^^^^^^^^^^^^^^^
>   File "/Users/friedahuang/Desktop/moonshot-v2/.conda/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>                 ^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/friedahuang/Documents/llama-stack-apps/examples/agents/vacation.py", line 54, in main
>     asyncio.run(run_main(host, port, disable_safety))
>   File "/Users/friedahuang/Desktop/moonshot-v2/.conda/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/Users/friedahuang/Desktop/moonshot-v2/.conda/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/friedahuang/Desktop/moonshot-v2/.conda/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/Users/friedahuang/Documents/llama-stack-apps/examples/agents/vacation.py", line 37, in run_main
>     await execute_turns(
>   File "/Users/friedahuang/Documents/llama-stack-apps/examples/agents/multi_turn.py", line 54, in execute_turns
>     async for log in EventLogger().log(iterator):
>   File "/Users/friedahuang/Desktop/moonshot-v2/.conda/lib/python3.11/site-packages/llama_stack_client/lib/agents/event_logger.py", line 58, in log
>     async for chunk in event_generator:
>   File "/Users/friedahuang/Documents/llama-stack-apps/common/execute_with_custom_tools.py", line 55, in execute_turn
>     if chunk.event.payload.event_type != "turn_complete":
>        ^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'payload'
> ```
> 
> ```
> Traceback (most recent call last):
>   File "/opt/anaconda3/envs/llamastack-csye7230-searchagent-stack/lib/python3.10/site-packages/llama_stack/distribution/server/server.py", line 206, in sse_generator
>     async for item in event_gen:
>   File "/opt/anaconda3/envs/llamastack-csye7230-searchagent-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/agents/agents.py", line 138, in _create_agent_turn_streaming
>     async for event in agent.create_and_execute_turn(request):
>   File "/opt/anaconda3/envs/llamastack-csye7230-searchagent-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 179, in create_and_execute_turn
>     async for chunk in self.run(
>   File "/opt/anaconda3/envs/llamastack-csye7230-searchagent-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 244, in run
>     async for res in self.run_multiple_shields_wrapper(
>   File "/opt/anaconda3/envs/llamastack-csye7230-searchagent-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/agents/agent_instance.py", line 299, in run_multiple_shields_wrapper
>     await self.run_multiple_shields(messages, shields)
>   File "/opt/anaconda3/envs/llamastack-csye7230-searchagent-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/agents/safety.py", line 37, in run_multiple_shields
>     responses = await asyncio.gather(
>   File "/opt/anaconda3/envs/llamastack-csye7230-searchagent-stack/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 155, in run_shield
>     return await self.routing_table.get_provider_impl(shield_type).run_shield(
>   File "/opt/anaconda3/envs/llamastack-csye7230-searchagent-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/safety/safety.py", line 77, in run_shield
>     res = await shield.run(messages)
>   File "/opt/anaconda3/envs/llamastack-csye7230-searchagent-stack/lib/python3.10/site-packages/llama_stack/providers/impls/meta_reference/safety/llama_guard.py", line 187, in run
>     async for chunk in self.inference_api.chat_completion(
>   File "/opt/anaconda3/envs/llamastack-csye7230-searchagent-stack/lib/python3.10/site-packages/llama_stack/distribution/routers/routers.py", line 94, in chat_completion
>     provider = self.routing_table.get_provider_impl(model)
>   File "/opt/anaconda3/envs/llamastack-csye7230-searchagent-stack/lib/python3.10/site-packages/llama_stack/distribution/routers/routing_tables.py", line 93, in get_provider_impl
>     raise ValueError(f"`{routing_key}` not registered")
> ValueError: `Llama-Guard-3-8B` not registered
> ```
> 
> ```
> version: '2'
> built_at: '2024-10-14T22:51:08.838065'
> image_name: csye7230-searchagent-stack
> docker_image: null
> conda_env: csye7230-searchagent-stack
> apis:
> - inference
> - safety
> - agents
> - memory
> - telemetry
> providers:
>   inference:
>   - provider_id: remote::ollama
>     provider_type: remote::ollama
>     config:
>       host: localhost
>       port: 11434
>   safety:
>   - provider_id: meta-reference
>     provider_type: meta-reference
>     config:
>       llama_guard_shield:
>         model: Llama-Guard-3-8B
>         excluded_categories: []
>       enable_prompt_guard: false
>   agents:
>   - provider_id: meta-reference
>     provider_type: meta-reference
>     config:
>       persistence_store:
>         namespace: null
>         type: sqlite
>         db_path: /Users/friedahuang/.llama/runtime/kvstore.db
>   memory:
>   - provider_id: remote::pgvector
>     provider_type: remote::pgvector
>     config:
>       host: localhost
>       port: 5432
>       db: remote::pgvector
>       user: llamastack_user
>       password: attentionisallyouneed
>   telemetry:
>   - provider_id: meta-reference
>     provider_type: meta-reference
>     config: {}
> ```

Update: 
Got it working!!

--disable-safety solved the safety issue. After that, it wasn't able to recognize Ollama models, resulting in `Llama-3.1-8B` not registered. Turns out the original url for Ollama `http://localhost:11434` wasn't working as expected. Only after changing it to `http://127.0.0.1:11434` does it solve the issue.

**Comment by yanxi0830** [comment]
> Update: Got it working!!
> 
> --disable-safety solved the safety issue. After that, it wasn't able to recognize Ollama models, resulting in `Llama-3.1-8B` not registered. Turns out the original url for Ollama `http://localhost:11434` wasn't working as expected. Only after changing it to `http://127.0.0.1:11434` does it solve the issue.

Awesome! For the issue with safety on `ValueError: `Llama-Guard-3-8B` not registered`. You will need to have the `Llama-Guard-3-8B` served either via inline (meta-reference running locally) or via an remote provider. Then add the following to the run.yaml config's.  

E.g. where `Llama-Guard-3-8B` is serving on `http://127.0.0.1:5010` via TGI. 
```yaml
inference:
  - provider_id: remote::ollama
    provider_type: remote::ollama
    config:
      host: 127.0.0.1
      port: 11434
  - provider_id: tgi-safety
    provider_type: remote::tgi
    config:
      url: http://127.0.0.1:5010
```

E.g. where `Llama-Guard-3-8B` is running locally. 
```
  - provider_id: meta-reference
    provider_type: meta-reference
    config:
      model: Llama-Guard-3-1B
      quantization: null
      torch_seed: null
      max_seq_len: 4096
      max_batch_size: 1
```
